export const SPOTS = [
  {
    id: "takapuna",
    name: "Takapuna Beach",
    lat: -36.7875,
    lon: 174.7735,
    coast: "east",
    shoreFacing: 70,
    preferredCenter: 50,
    preferredWidth: 90,
    bestTide: "mid-high",
    tideCritical: false,
    travelFromCbdMin: 25,
    parkingCost: "paid",
    skillMin: "beginner",
    popularity: 92,
    remote: false,
    hazards: [
      "Swimmers and paddle craft in the inner flags",
      "Southerly is offshore — do not launch",
      "Rocks at the south end"
    ],
    launchLand: "Mid-beach, well north of the patrol flags when busy.",
    parking: "The Strand and Huron Street. Paid in summer.",
    localTips: "Best on NE–E. Can get crowded after work. Walk further north for space."
  },
  {
    id: "orewa",
    name: "Orewa Beach",
    lat: -36.586,
    lon: 174.695,
    coast: "east",
    shoreFacing: 70,
    preferredCenter: 70,
    preferredWidth: 100,
    bestTide: "all",
    tideCritical: false,
    travelFromCbdMin: 40,
    parkingCost: "free",
    skillMin: "beginner",
    popularity: 74,
    remote: false,
    hazards: ["Swimmers in summer", "Estuary current at the south end"],
    launchLand: "Long sandy beach; more space at the north end.",
    parking: "Marine View and beachfront reserves. Free.",
    localTips: "Friendly for self-sufficient beginners. SE can work further north."
  },
  {
    id: "long-bay",
    name: "Long Bay",
    lat: -36.685,
    lon: 174.75,
    coast: "east",
    shoreFacing: 80,
    preferredCenter: 60,
    preferredWidth: 90,
    bestTide: "low-mid",
    tideCritical: false,
    travelFromCbdMin: 35,
    parkingCost: "paid",
    skillMin: "beginner",
    popularity: 48,
    remote: false,
    hazards: ["Marine reserve rules", "Family beach — give space"],
    launchLand: "North of the main flags on a dropping or low tide.",
    parking: "Regional park carpark. Paid.",
    localTips: "More walking at high tide. Good when Takapuna is packed."
  },
  {
    id: "narrow-neck",
    name: "Narrow Neck",
    lat: -36.786,
    lon: 174.801,
    coast: "east",
    shoreFacing: 70,
    preferredCenter: 55,
    preferredWidth: 80,
    bestTide: "mid-high",
    tideCritical: true,
    travelFromCbdMin: 30,
    parkingCost: "free",
    skillMin: "intermediate",
    popularity: 44,
    remote: false,
    hazards: ["Reef and rocks at low tide", "Small launch window"],
    launchLand: "Sandy patch at mid to high tide only.",
    parking: "Clifton Road / beachfront. Free.",
    localTips: "Shorter fetch than Takapuna. Skip it on a spring low."
  },
  {
    id: "omaha",
    name: "Omaha Beach",
    lat: -36.333,
    lon: 174.775,
    coast: "east",
    shoreFacing: 75,
    preferredCenter: 70,
    preferredWidth: 100,
    bestTide: "mid",
    tideCritical: false,
    travelFromCbdMin: 70,
    parkingCost: "free",
    skillMin: "beginner",
    popularity: 61,
    remote: true,
    hazards: ["Sandbar dump on some tides", "Long drive if it dies"],
    launchLand: "Main beach, away from the surf club flags.",
    parking: "Beachfront reserves. Free.",
    localTips: "Worth the drive on a solid E–NE. Can be punchy on the bar."
  },
  {
    id: "point-chev",
    name: "Point Chevalier / Meola",
    lat: -36.86,
    lon: 174.71,
    coast: "harbour",
    shoreFacing: 240,
    preferredCenter: 240,
    preferredWidth: 80,
    bestTide: "incoming-high",
    tideCritical: true,
    travelFromCbdMin: 20,
    parkingCost: "free",
    skillMin: "beginner",
    popularity: 52,
    remote: false,
    hazards: [
      "Strong harbour current",
      "Shallow reef at low tide",
      "Outgoing tide can sweep you east"
    ],
    launchLand: "Incoming to high tide only. Do not kite the outgoing spring tide.",
    parking: "Meola Reef / Pt Chev beach. Free.",
    localTips: "Flat-water classroom when the tide is right. Confirm official tide before you go."
  },
  {
    id: "muriwai",
    name: "Muriwai Beach",
    lat: -36.831,
    lon: 174.434,
    coast: "west",
    shoreFacing: 270,
    preferredCenter: 250,
    preferredWidth: 90,
    bestTide: "mid",
    tideCritical: false,
    travelFromCbdMin: 50,
    parkingCost: "free",
    skillMin: "intermediate",
    popularity: 78,
    remote: false,
    hazards: ["Rips", "Dumping shorebreak", "Easterly is offshore"],
    launchLand: "South of the main surf crowd. Walk if the dump is heavy.",
    parking: "Main beach carpark. Free.",
    localTips: "The go-to west-coast kite beach on SW–W. Not a first-session spot."
  },
  {
    id: "karioitahi",
    name: "Karioitahi Beach",
    lat: -37.28,
    lon: 174.65,
    coast: "west",
    shoreFacing: 250,
    preferredCenter: 240,
    preferredWidth: 100,
    bestTide: "all",
    tideCritical: false,
    travelFromCbdMin: 75,
    parkingCost: "free",
    skillMin: "intermediate",
    popularity: 58,
    remote: true,
    hazards: ["Remote", "Rips", "Limited help if you lose gear"],
    launchLand: "Long beach — pick a quieter pocket.",
    parking: "Clifftop carpark then walk down. Free.",
    localTips: "Big west-coast canvas. Solo kiters should tell someone and take a GPS tracker."
  },
  {
    id: "piha",
    name: "Piha",
    lat: -36.953,
    lon: 174.468,
    coast: "west",
    shoreFacing: 270,
    preferredCenter: 250,
    preferredWidth: 70,
    bestTide: "mid",
    tideCritical: false,
    travelFromCbdMin: 50,
    parkingCost: "free",
    skillMin: "advanced",
    popularity: 28,
    remote: false,
    hazards: ["Heavy beach", "Rips", "Crowded surf", "Rocks at Lion Rock"],
    launchLand: "Only if you already know Piha. Most kiters should choose Muriwai.",
    parking: "South or North Piha. Free.",
    localTips: "Rarely the best kite option. Advanced only."
  }
];

export const DEFAULT_LOCATION = {
  name: process.env.DEFAULT_LOCATION || "Auckland",
  lat: Number(process.env.LATITUDE || -36.8509),
  lon: Number(process.env.LONGITUDE || 174.7645)
};

export function getSpot(id) {
  return SPOTS.find((spot) => spot.id === id) || null;
}

export function builtInAndCustomSpots(customSpots = []) {
  return [...SPOTS, ...customSpots];
}
